version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: java
    depends_on:
      - db
    environment:
      - PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8081
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
     - 5432:5432
    volumes:
      - data_pg:/var/lib/postgresql/data
      
  react:
    image: 'react'
    build:
      context: ./nauchki-react-main
    ports:
     - 80:3000
    container_name: react

volumes:
  data_pg:
